name: MagicSpells
main: com.nisovin.magicspells.MagicSpells
version: 3.0-b2
author: nisovin
softdepend: [Vault,WorldGuard,Residence]
commands:
    magicspellcast:
        description: Cast a spell
        usage: /<command>
        aliases: [cast,c]
    magicspellmana:
        description: Show mana bar
        usage: /<command>
        aliases: [mana]