name: MagicSpells
main: com.nisovin.MagicSpells.MagicSpells
version: 0.7.3
author: nisovin
commands:
    cast:
        description: Cast a spell
        usage: /<command>
        aliases: [c]
    mana:
        description: Show mana bar
        usage: /<command>
        aliases: [m]