name: CodeLock
main: com.nisovin.codelock.CodeLock
version: 1.2
author: nisovin
permissions:
    codelock.bypass:
        description: Bypass locks
        default: op
    codelock.lock:
        description: Allow locking
        default: true