name: CodeLock
main: com.nisovin.codelock.CodeLock
version: 1.2
author: nisovin
permissions:
    codelock.bypass:
        description: Bypass all locks and protections
        default: op
    codelock.lock:
        description: Allow adding and removing code locks
        default: true