name: MagicSpellsShop
version: 1.3
main: com.nisovin.magicspells.shop.MagicSpellsShop
author: nisovin
depend: [MagicSpells]
softdepend: [Vault]
permissions:
    magicspells.createsignshop:
        description: Create a spell shop
        default: op