name: BookWorm
main: com.nisovin.bookworm.BookWorm
version: 1.4
softdepend: [BukkitContrib]
commands:
    bookworm:
        description: Basic bookworm command
        usage: /<command>
        aliases: [bw, write, w]