name: DwarvesVsZombies
version: 1.0
main: com.nisovin.dvz.DvZ

depend: [ MagicSpells, BrucesGym ]

commands:
    startgame:
        description: Starts the game
        permission: dvz.admin
    override:
        description: Overrides the auto system
        permission: dvz.admin
    releasemonsters:
        description: Releases the monsters
        permission: dvz.admin
    hide:
        description: Hides player identity
        permission: dvz.hide
        
permissions:
    dvz.admin:
        description: Perm for admin commands
        default: op
    dvz.ignore:
        description: Ignore this player for the game
        default: false
    dvz.hide:
        description: Allows a player to hide
        default: false