name: BarnYardBlitz
version: 1.0
main: com.nisovin.barnyard.BarnYardBlitz

depend: [MagicSpells]

commands:
    score:
        description: Check the score
        usage: /<command>
        permission: barnyard.score
    setteamspawn:
        description: Sets the team's default spawn location
        usage: /<command> <team> [area name]
        permission: barnyard.setteamspawn
    addspawnpoint:
        description: Adds a spawn point
        usage: /<command>
        permission: barnyard.addspawnpoint
    removespawnpoints:
        description: Removes all spawn points in the area you are in
        usage: /<command>
        permission: barnyard.removespawnpoints
    viewspawnpoints:
        description: Views spawn points in the area you are in
        usage: /<command>
        permission: barnyard.viewspawnpoints
    startgame:
        description: Starts the game
        usage: /<command>
        permission: barnyard.startgame
    setteam:
        description: Set a player's team
        usage: /<command> <player> <team>
        permission: barnyard.setteam
    pigcaptain:
        description: Chooses a pig captain
        usage: /<command>
        permission: barnyard.pigcaptain
    capture:
        description: Capture the area you are standing in for the specified team
        usage: /<command> [id] <team>
        permission: barnyard.capture
    captureid:
        description: Checks what this area's id is.
        usage: /<command>
        permission: barnyard.captureid
        aliases: [areaid, zoneid, pointid]
    eliminate:
        description: Eliminates a team.
        usage: /<command> <team>
        permission: barnyard.eliminate
    stopgame:
        description: Stops the current game.
        usage: /<command>
        permission: barnyard.stopgame
    reloadgame:
        description: Reloads the game settings and reinitializes the game.
        usage: /<command>
        permission: barnyard.reloadgame
    gametimings:
        description: See game timings.
        usage: /<command>
        permission: barnyard.gametimings
    
permissions:
    barnyard.ignore:
        description: The player is ignored by the game.
        default: false
    barnyard.score:
        description: Allows usage of the score command
        default: op
    barnyard.setteamspawn:
        description: Allows usage of the setteamspawn command
        default: op
    barnyard.addspawnpoint:
        description: Allows usage of the addspawnpoint command
        default: op
    barnyard.removespawnpoints:
        description: Allows usage of the removespawnpoints command
        default: op
    barnyard.viewspawnpoints:
        description: Allows usage of the viewspawnpoints command
        default: op
    barnyard.startgame:
        description: Allows usage of the startgame command
        default: op
    barnyard.setteam:
        description: Allows usage of the setteam command
        default: op
    barnyard.pigcaptain:
        description: Allows usage of pigcaptain command
        default: op
    barnyard.capture:
        description: Allows usage of the capture command
        default: op
    barnyard.captureid:
        description: Allows usage of the captureid command
        default: op
    barnyard.eliminate:
        description: Allows usage of the eliminate command
        default: op
    barnyard.stopgame:
        description: Allows usage of the stopgame command
        default: op
    barnyard.reloadgame:
        description: Allows usage of the reloadgame command
        default: op
    barnyard.gametimings:
        default: op
    barnyard.*:
        description: Allows access to all barnyard commands
        default: op
        children:
            barnyard.score: true
            barnyard.setteamspawn: true
            barnyard.addspawnpoint: true
            barnyard.removespawnpoints: true
            barnyard.viewspawnpoints: true
            barnyard.startgame: true
            barnyard.setteam: true
            barnyard.pigcaptain: true
            barnyard.capture: true
            barnyard.captureid: true
            barnyard.eliminate: true
            barnyard.stopgame: true
            barnyard.reloadgame: true
            