name: CoopPlay
main: com.nisovin.coop.CoopPlugin
version: 1.0
commands:
    coopparty:
        description: Party!
        aliases: [party]
    coopinvite:
        description: Invite a player to your party.
        usage: /<command> <name>
        aliases: invite
permissions:
    healthplates.nocolor:
        description: Prevents the player from having their nameplate colored.
        default: false
    healthplates.noview:
        description: Prevents the player from seeing colored nameplates.
        default: false