general:
    str-cast-usage: |
        Usage: /cast <spell>. 
        Use /cast list to see a list of spells.
    str-unknown-spell: You do not know a spell with that name.
    str-spell-change: You are now using the %s spell.
    str-on-cooldown: That spell is on cooldown (%c seconds remaining).
    str-missing-reagents: You do not have the required reagents for that spell.
    str-cant-cast: You can't cast that spell right now.
    str-console-name: Admin
    text-color: 3
    broadcast-range: 20
    use-permissions: false
    use-health-bars: false
    ops-have-all-spells: true
    cast-for-free:
        - admin1
        - admin2
        - joemagicuser
    freecast-no-cooldown: true
    ignore-default-bindings: false
    mana:
        enable-mana-bars: true
        max-mana: 100
        mana-bar-prefix: "Mana:"
        mana-bar-size: 35
        color-full: 10
        color-empty: 0
        regen-tick-seconds: 5
        regen-percent: 5
        show-mana-on-use: false
        show-mana-on-regen: false
        show-mana-on-wood-tool: true
        tool-slot: 8
        
spells:

    list:
        name: list
        description: List all the spells you know.
        str-prefix: "Known spells:"
        str-no-spells: You do not know any spells.
    help:
        name: help
        description: Get information about a specified spell.
        str-usage: "Usage: /cast help <spell>"
        str-no-spell: You do not know a spell by that name.
        str-desc-line: "%s - %d"
        str-cost-line: "Cost: %c"
    teach:
        name: teach
        description: Teach a spell to another player.
        str-usage: "Usage: /cast teach <target> <spell>"
        str-no-target: No such player.
        str-no-spell: You do not know a spell by that name.
        str-cant-teach: You can't teach that spell.
        str-cant-learn: That person cannot learn that spell.
        str-cast-self: You have taught %t the %s spell.
        str-cast-target: "%a has taught you the %s spell."
    forget:
        name: forget
        description: Make a player forget a spell.
        str-usage: "Usage: /cast forget <target> <spell>"
        str-no-target: No such player.
        str-no-spell: You do not know a spell by that name.
        str-doesnt-know: That person does not know that spell.
        str-cast-self: You made %t forget the %s spell.
        str-cast-target: "%a has made you forget the %s spell."
    spellbook:
        name: spellbook
        description: Create a spellbook that teaches a spell.
        default-uses: -1
        destroy-when-used-up: false
        str-use: "Usage: /cast spellbook <spell> [uses]"
        str-cast-self: You have created a spellbook with the %s spell.
        str-no-spell: You do not know a spell by that name.
        str-cant-teach: You can't create a spellbook with that spell.
        str-no-target: You must target a bookcase to create a spellbook.
        str-has-spellbook: That bookcase already has a spellbook.
        str-cant-destroy: You cannot destroy a bookcase with a spellbook.
        str-cant-learn: You cannot learn the spell in this spellbook.
        str-already-known: You already know the %s spell.
        str-learned: You have learned the %s spell!
    bind:
        name: bind
        enable: true
        description: Binds a spell to a wand item.
        str-cast-self: You have successfully bound the %s spell to the item you are holding.
        str-usage: You must specify a spell name and hold an item in your hand.
        str-no-spell: You do not know a spell by that name.
        str-cant-bind: That spell cannot be bound to an item.

    blink:
        name: blink
        description: Teleport a short distance.
        cast-item: 280
        cooldown: 8
        range: 25
        smoke-trail: true
        cost:
            - 331 2
        str-cost: 2 redstone dust
        str-cast-self: You blink away!
        str-cast-others: "%a blinks away!"
        str-cant-blink: You cannot blink there.
    build:
        name: build
        description: Build blocks from far away.
        cast-item: 294
        cooldown: 2
        range: 25
        slot: 0
        consume-block: true
        show-effect: true
        check-plugins: true
        allowed-types: 1,2,3,4,5,12,13,17,20,22,24,35,41,42,43,44,45,47,48,49,50,53,57,65,67,80,85,87,88,89,91,92
        str-invalid-block: You can't build that block.
        str-cant-build: You can't build there.
    combust:
        name: combust
        description: Set a target on fire.
        cast-item: 283
        cooldown: 10
        range: 20
        obey-los: true
        fire-ticks: 100
        target-players: false
        check-plugins: true
        cost:
            - 331 1
            - 263 1
        str-cost: 1 redstone dust and 1 coal
        str-no-target: No target found.
    entomb:
        name: entomb
        description: Encase an enemy in glass.
        cast-item: 280
        cooldown: 5
        range: 15
        obey-los: true
        target-players: false
        tomb-block-type: 20
        tomb-duration: 20
        cost:
            - 331 3
            - 20 1
        str-cost: 3 redstone dust and 1 glass
        str-no-target: No target found.
    explode:
        name: explode
        description: Create an explosion.
        cast-item: 283
        cooldown: 30
        range: 25
        explosion-size: 4
        backfire-chance: 3
        check-plugins: true
        cost:
            - 331 5
            - 289 1
        str-cost: 5 redstone dust and 1 gunpowder
        str-no-target: You cannot create an explosion there.
        str-cast-self: Boom!
        str-cast-others: Boom!
    fireball:
        name: fireball
        description: Throw a fiery ball of destruction.
        cast-item: 283
        cooldown: 15
        range: 30
        additional-damage: 0
        no-fire: false
        cost: 
            - 331 3
            - 263 2
        str-cost: 3 redstone dust and 2 coal
        str-no-target: You cannot throw a fireball there.
        str-cast-self: You throw a fiery ball of destruction!
        str-cast-others: "%a throws a fiery ball of destruction!"
    firenova:
        name: firenova
        description: Summon an expanding ring of fire.
        cast-item: 283
        cooldown: 10
        range: 5
        tick-speed: 10
        check-plugins: true
        cost:
            - 331 2
            - 263 1
        str-cost: 2 redstone dust and 1 coal
        str-cast-self: You summon an expanding ring of fire.
        str-cast-others: "%a summons an expanding ring of fire."
    flamewalk:
        name: flamewalk
        description: Burn your enemies around you as you walk.
        cast-item: 317
        cooldown: 30
        range: 8
        fire-ticks: 100
        tick-interval: 100
        target-players: false
        duration: 120
        cost:
            - 331 5
            - 263 2
        use-cost:
            - 331 1
        use-cost-interval: 15
        str-cost: 5 redstone, 2 coal, plus 1 redstone occasionally
        str-cast-self: You begin to burn your enemies around you.
        str-fade: You are no longer burning your enemies.
    forcepush:
        name: forcepush
        description: Push back your enemies.
        cast-item: 280
        cooldown: 8
        range: 10
        pushback-force: 30
        additional-vertical-force: 15
        max-vertical-force: 20
        target-players: false
        cost:
            - 331 3
        str-cost: 3 redstone dust
        str-cast-self: You push back your enemies!
        str-cast-others: "%a pushes back his enemies."
    frostwalk:
        name: frostwalk
        description: Lets you walk on water.
        cast-item: 317
        size: 2
        leave-frozen: false
        cooldown: 30
        cost:
            - 331 6
        use-cost:
            - 331 1
        use-cost-interval: 50
        str-cost: 6 redstone, plus 1 redstone every 50 blocks
        str-cast-self: You can now walk on water!
        str-cast-others: "%a can now walk on water!"
        str-fade: You can no longer walk on water.
    gate:
        name: gate
        description: Teleport to spawn.
        can-cast-with-item: false
        world: CURRENT
        coordinates: SPAWN
        use-spell-effect: true
        cost:
            - 331 1
            - 265 1
        str-cast-self: You have teleported to spawn.
        str-cast-others: "%a teleports!"
        str-gate-failed: Unable to teleport.
    gills:
        name: gills
        description: Allows you to breath underwater.
        cast-item: 294
        glass-head-effect: true
        cooldown: 60
        duration: 300
        num-uses: 5
        cost:
            - 331 3
        use-cost:
            - 331 1
        use-cost-interval: 1
        str-cost: 3 redstone dust, plus 1 every few seconds
        str-cast-self: You form gills on your neck!
        str-fade: Your gills disappear.
    heal:
        name: heal
        description: Heals a target player.
        cast-item: 280
        heal-amount: 10
        obey-los: true
        cooldown: 0
        range: 12
        cost:
            - 331 2
        str-cost: 2 redstone dust
        str-cast-self: You have healed %t.
        str-cast-target: "%a has healed you."
        str-no-target: No target to heal.
        str-max-health: "%t is already at max health."
    invulnerability:
        name: invulnerability
        description: Makes you invulnerable to damage.
        cast-item: 280
        damage-causes:
            - block explosion
            - contact
            - drowning
            - entity attack
            - entity explosion
            - fall
            - fire
            - fire tick
            - lava
            - lightning
            - suffocation
        duration: 60
        cost: 
            - 331 5
        use-cost: 
            - 331 1
        use-cost-interval: 5
        str-cost: 5 redstone dust, plus 1 occasionally
        str-cast-self: You feel your skin harden.
        str-cast-others: "%a's skin hardens."
        str-fade: You feel your skin return to normal.
    lifewalk:
        name: lifewalk
        description: Flowers grow in your footsteps!
        cast-item: 317
        tick-interval: 15
        red-flower-chance: 15
        yellow-flower-chance: 15
        sapling-chance: 5
        tallgrass-chance: 25
        fern-chance: 15
        cost:
            - 331 2
            - 38 1
        use-cost:
            - 331 1
        use-cost-interval: 20
        str-cost: 2 redstone and 1 rose, plus 1 redstone every few seconds
        str-cast: Flowers grow in your footsteps!
        str-cast-others: Flowers grow in %a's footsteps!
        str-fade: Flowers no longer grow in your footsteps.
    lightning:
        name: lightning
        description: Call down lightning.
        cast-item: 283
        cooldown: 15
        range: 20
        no-damage: false
        require-entity-target: false
        obey-los: true
        target-players: false
        check-plugins: true
        cost:
            - 331 2
        str-cost: 2 redstone dust
        str-cast-self: You call down lightning.
        str-cast-others: "%a calls down lightning."
        str-no-target: Unable to find target.
    lightwalk:
        name: lightwalk
        description: Light your path.
        cast-item: 317
        cost:
            - 331 3
            - 50 3
        use-cost:
            - 331 1
        use-cost-interval: 25
        str-cost: 3 redstone and 3 torches, plus 1 redstone occasionally
        str-cast-self: Light appears at your feet.
        str-fade: The light at your feet goes out.
    mark:
        name: mark
        description: Marks your location for later recall.
        cooldown: 43200
        permanent-marks: true
        cost:
            - 331 5
            - 265 5
        str-cost: 5 redstone dust and 5 iron bars
        str-cast-self: You have marked your location.
    minion:
        name: minion
        description: Summons an undead minion to aid you.
        cast-item: 280
        cooldown: 60
        duration: 60
        mob-chances:
            Zombie 75
            Skeleton 25
        prevent-sun-burn: true
        target-players: false
        cost:
            - 331 2
            - 352 1
        str-cost: 2 redstone dust and 1 bone
        str-cast-self: You summon an undead minion.
        str-cast-others: "%a has summoned an undead minion."
        str-fade: Your undead minion dies.
    prayer:
        name: prayer
        description: Heals yourself for five hearts.
        cast-item: 38
        cooldown: 15
        amount-healed: 10
        cost:
            - 331 1
        str-cost: 1 redstone dust
        str-cast-self: You have healed yourself.
        str-at-full-health: You are already at full health.
    purge:
        name: purge
        description: Kill all monsters and animals around you.
        cast-item: 283
        cooldown: 60
        range: 15
        cost:
            - 331 3
        str-cost: 3 redstone dust
        str-cast-self: You purge all life around you.
        str-cast-others: "%a purges all nearby life."
    recall:
        name: recall
        description: Teleports you to your marked location.
        cooldown: 300
        max-range: -1
        allow-cross-world: true
        cost:
            - 331 1
            - 265 1
        str-cost: 1 redstone dust and 1 iron bar
        str-cast-self: You teleport to your marked location.
        str-no-mark: You have not marked a location to recall to.
        str-other-world: You cannot recall to another world.
        str-too-far: Your marked location is too far away.
        str-cast-others: "%a disappears!"
    safefall:
        name: safefall
        description: Allows you to fall without taking damage.
        cast-item: 294
        cooldown: 60
        duration: 300
        num-uses: 5
        cost:
            - 331 2
        use-cost:
            - 288 1
        use-cost-interval: 1
        str-cost: 2 redstone dust, plus 1 feather each time you fall
        str-cast-self: You feel lighter.
        str-fade: Your normal weight returns.
    stealth:
        name: stealth
        description: Become invisible to monsters.
        cast-item: 280
        cooldown: 60
        duration: 20
        cost:
            - 331 3
        str-cost: 3 redstone dust
        str-cast-self: You become invisble to monsters.
        str-fade: You are no longer invisible to monsters.
    stonevision:
        name: stonevision
        description: See through stone.
        cast-item: 317
        range: 4
        transparent-type: 1
        cooldown: 60
        duration: 30
        cost: 
            - 331 4
            - 1 2
            - 20 2
        str-cost: 4 redstone dust, 2 stone and 2 glass
        str-cast-self: You can see through stone!
        str-fade: You can no longer see through stone.
    telekinesis:
        name: telekinesis
        description: Manipulate switches and buttons remotely.
        cast-item: 280
        cooldown: 15
        range: 20
        cost:
            - 331 1
        str-cost: 1 redstone dust
        str-no-target: You must target a switch or button.
    volley:
        name: volley
        description: Send a volley of arrows at your targeted location.
        cast-item: 283
        cooldown: 45
        range: 30
        arrows: 10
        speed: 20
        spread: 150
        cost:
            - 331 3
            - 262 2
        str-cost: 3 redstone dust and 2 arrows
        str-cast-self: You fire a volley of magic arrows.
        str-cast-others: "%a fires a volley of arrows."
        str-no-target: No target found.
    wall:
        name: wall
        description: Creates a temporary wall to block your enemies.
        cast-item: 280
        cooldown: 15
        range: 3
        wall-width: 5
        wall-height: 3
        wall-type: 45
        wall-duration: 15
        cost:
            - 331 2
            - 1 2
        str-cost: 2 redstone dust and 2 stone
        str-no-target: Unable to create a wall.
    windwalk:
        name: windwalk
        description: Lets you walk on a platform of air.
        cast-item: 317
        cooldown: 30
        cancel-on-logout: true
        cancel-on-teleport: true
        cost:
            - 331 5
            - 288 5
        use-cost:
            - 288 1
        use-cost-interval: 50
        str-cost: 5 redstone, 5 feathers, plus 1 feather every 50 blocks
        str-cast-self: You are now walking on air!
        str-cast-others: "%a is now walking on air!"
        str-fade: You are no longer walking on air.
    zap:
        name: zap
        description: Instantly destroys a block.
        cast-item: 294
        cooldown: 0
        disallowed-blocks: 0,7
        range: 15
        cost:
            - 331 1
        str-cost: 1 redstone dust
        str-cast-self: You zapped a block.
        str-cant-zap: You can't zap that.
        
    external:
        name: gianttree
        enabled: false
        description: Create a giant tree!
        cooldown: 300
        can-cast-by-command: true
        can-cast-with-item: false
        command-to-execute: gt 25 4
        command-to-block: gt
        cost:
            - 331 10
            - 6 5
        str-cost: 10 redstone dust and 5 saplings
        str-cast-self: You grow a tree!
        str-cant-use-command: &4You don't have permission to do that.