name: MagicSpells
main: com.nisovin.magicspells.MagicSpells
version: 2.1
author: nisovin
softdepend: [BookWorm,WorldGuard]
commands:
    magicspellcast:
        description: Cast a spell
        usage: /<command>
        aliases: [cast,c]
    magicspellmana:
        description: Show mana bar
        usage: /<command>
        aliases: [mana,m]
permissions:
    magicspells.noreagents:
        description: Cast without needing reagents
        default: op
    magicspells.nocooldown:
        description: Spells do not cause cooldowns
        default: op
    magicspells.notarget:
        description: Cannot be targeted by spells
        default: false
    magicspells.silent:
        description: Cast spells without spell text messages
        default: false
    magicspells.advanced:
        description: Advanced spell functionality
        default: op