name: MagicSpells
main: com.nisovin.magicspells.MagicSpells
version: 2.12
author: nisovin
softdepend: [WorldGuard,Residence]
commands:
    magicspellcast:
        description: Cast a spell
        usage: /<command>
        aliases: [cast,c]
    magicspellmana:
        description: Show mana bar
        usage: /<command>
        aliases: [mana]