name: MagicSpells
main: com.nisovin.MagicSpells.MagicSpells
version: 1.0.2
author: nisovin
softdepend: [BookWorm,WorldGuard]
commands:
    magicspellcast:
        description: Cast a spell
        usage: /<command>
        aliases: [cast,c]
    magicspellmana:
        description: Show mana bar
        usage: /<command>
        aliases: [mana,m]