auto-start-time: 0
game-duration: 600
spawn-delay: 200

points-gained-per-kill: 1
points-stolen-per-kill: 8
points-lost-per-death: 8

weapon-items:
  - stone
  - brick
heal-items:
  - bucket
  - potion
weapon-item-count: 2
heal-item-count: 1

drop-items:
  - blaze_rod
  - stick
drop-item-interval: 600
max-drop-count: 3