name: YAPP
description: Yet Another Permission Plugin
author: nisovin
version: 0.1
main: com.nisovin.yapp.MainPlugin
softdepend: [Vault]
commands:
    yapp:
        description: Modify permission settings.
        aliases: [permissions, permission, perms, perm, yap]
        permission: yapp.admin
    yapppromote:
        description: Promotes a player to the next group.
        aliases: [promote]
        permission: yapp.promote
    yappdemote:
        description: Demotes a player to the previous group.
        aliases: [demote]
        permission: yapp.demote
permissions:
    yapp.build:
        description: Allows the player to build.
        default: false
    yapp.admin:
        description: Modify permission settings.
        default: op