name: HealthPlates
version: 2.0
main: com.nisovin.healthplates.HealthPlatesPlugin
author: nisovin
commands:
    healthplates:
        description: Enable or disable healthplates functionality
        usage: "Usage: /healthplates <enable|disable|update <player>>"
permissions:
    healthplates.nocolor:
        description: Prevents the player from having their nameplate colored.
        default: false
    healthplates.noview:
        description: Prevents the player from seeing colored nameplates.
        default: false