name: MagicSpellsShop
version: 1.1
main: com.nisovin.magicspells.shop.MagicSpellsShop
author: nisovin
depend: [MagicSpells,Vault]
permissions:
    magicspells.createsignshop:
        description: Create a spell shop
        default: op