name: AccessControl
version: 1.0
main: com.nisovin.accesscontrol.AccessControl
author: nisovin

commands:
    votekick:
        description: Vote to kick a guest player.
        permission: access.whitelist
        usage: /<command> <playername>