name: YAPP
description: Yet Another Permission Plugin
author: nisovin
version: 0.2
main: com.nisovin.yapp.MainPlugin
softdepend: [Vault]
commands:
    yapp:
        description: Modify permission settings.
        aliases: [permissions, permission, perms, perm, yap]
        permission: yapp.admin
    yapppromote:
        description: Promotes a player to the next group.
        usage: /<command> [o:]<player> [world]
        aliases: [promote]
        permission: yapp.promote
    yappdemote:
        description: Demotes a player to the previous group.
        usage: /<command> [o:]<player> [world]
        aliases: [demote]
        permission: yapp.demote
permissions:
    yapp.build:
        description: Allows the player to build.
        default: false
    yapp.admin:
        description: Modify permission settings.
        default: op
    yapp.promote:
        description: General permission to promote players.
        default: op
    yapp.demote:
        description: General permission to demote players.
        default: op
    yapp.promote.*:
        description: Promote players on any ladder.
        default: op
    yapp.demote.*:
        description: Demote players on any ladder.
        default: op