datestr: "Today is %w, %m %d, %y"
dayannounce: true
monthnames: January,February,March,April,May,June,July,August,September,October,November,December
monthdays: 31,28,31,30,31,30,31,31,30,31,30,31
ordinals: 1st,2nd,3rd,4th,5th,6th,7th,8th,9th,10th,11th,12th,13th,14th,15th,16th,17th,18th,19th,20th,21st,22nd,23rd,24th,25th,26th,27th,28th,29th,30th,31st
weekdays: Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday
yearoffset: 2000
yeartag: "A.D."
world: "world"
daychangeoffset: 0
timecheckinterval: 1000
ignorebigchanges: false
debug: false